# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (test IS cluster1) AND (symptoms IS cluster1) AND (action IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (test IS cluster2) AND (symptoms IS cluster2) AND (action IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (test IS cluster3) AND (symptoms IS cluster3) AND (action IS cluster3) THEN (OUTPUT IS fun3)"
RULE4 = "IF (test IS cluster4) AND (symptoms IS cluster4) AND (action IS cluster4) THEN (OUTPUT IS fun4)"
RULE5 = "IF (test IS cluster5) AND (symptoms IS cluster5) AND (action IS cluster5) THEN (OUTPUT IS fun5)"
FS.add_rules([RULE1, RULE2, RULE3, RULE4, RULE5])

FS.set_output_function('fun1', '0.370121+0.366037*test+0.100015*symptoms+-0.00744*action')
FS.set_output_function('fun2', '0.0+0.0*test+0.0*symptoms+0.0*action')
FS.set_output_function('fun3', '0.302772+0.313303*test+0.246548*symptoms+-0.010315*action')
FS.set_output_function('fun4', '0.0+0.0*test+0.0*symptoms+0.0*action')
FS.set_output_function('fun5', '0.33462+0.099827*test+0.32114*symptoms+0.005206*action')

FS_1 = FuzzySet(function=Gaussian_MF(0.639566, 0.352749), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(0.382943, 0.277501), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(0.781092, 0.342301), term='cluster3')
FS_4 = FuzzySet(function=Gaussian_MF(0.188893, 0.313134), term='cluster4')
FS_5 = FuzzySet(function=Gaussian_MF(0.152272, 0.278979), term='cluster5')
MF_test = LinguisticVariable([FS_1, FS_2, FS_3, FS_4, FS_5], concept='test')
FS.add_linguistic_variable('test', MF_test)

FS_6 = FuzzySet(function=Gaussian_MF(1.024214, 0.399249), term='cluster1')
FS_7 = FuzzySet(function=Gaussian_MF(0.805314, 0.303590), term='cluster2')
FS_8 = FuzzySet(function=Gaussian_MF(0.885475, 0.458445), term='cluster3')
FS_9 = FuzzySet(function=Gaussian_MF(0.177190, 0.297210), term='cluster4')
FS_10 = FuzzySet(function=Gaussian_MF(0.227750, 0.394848), term='cluster5')
MF_symptoms = LinguisticVariable([FS_6, FS_7, FS_8, FS_9, FS_10], concept='symptoms')
FS.add_linguistic_variable('symptoms', MF_symptoms)

FS_11 = FuzzySet(function=Gaussian_MF(1.680234, 0.862525), term='cluster1')
FS_12 = FuzzySet(function=Gaussian_MF(0.456023, 0.000255), term='cluster2')
FS_13 = FuzzySet(function=Gaussian_MF(-0.681262, 0.951561), term='cluster3')
FS_14 = FuzzySet(function=Gaussian_MF(0.479179, 0.000253), term='cluster4')
FS_15 = FuzzySet(function=Gaussian_MF(1.320198, 0.700417), term='cluster5')
MF_action = LinguisticVariable([FS_11, FS_12, FS_13, FS_14, FS_15], concept='action')
FS.add_linguistic_variable('action', MF_action)


# end of automatically generated code #