# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (test IS cluster1) AND (symptoms IS cluster1) AND (action IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (test IS cluster2) AND (symptoms IS cluster2) AND (action IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (test IS cluster3) AND (symptoms IS cluster3) AND (action IS cluster3) THEN (OUTPUT IS fun3)"
RULE4 = "IF (test IS cluster4) AND (symptoms IS cluster4) AND (action IS cluster4) THEN (OUTPUT IS fun4)"
RULE5 = "IF (test IS cluster5) AND (symptoms IS cluster5) AND (action IS cluster5) THEN (OUTPUT IS fun5)"
FS.add_rules([RULE1, RULE2, RULE3, RULE4, RULE5])

FS.set_output_function('fun1', '0.0+0.0*test+0.0*symptoms+0.0*action')
FS.set_output_function('fun2', '0.22117712788164107+0.3218101761285623*test+0.2280990729129299*symptoms+0.0*action')
FS.set_output_function('fun3', '0.0+0.0*test+0.0*symptoms+0.0*action')
FS.set_output_function('fun4', '0.2801740237561425+0.20825852786800433*test+0.1571492032107798*symptoms+0.021353160577518085*action')
FS.set_output_function('fun5', '0.26985724626341134+0.16729168772292594*test+0.2802723128986198*symptoms+-0.013028994618954987*action')

FS_1 = FuzzySet(function=Gaussian_MF(0.276909, 0.275322), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(0.509734, 0.213224), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(0.703862, 0.187427), term='cluster3')
FS_4 = FuzzySet(function=Gaussian_MF(0.260517, 0.188092), term='cluster4')
FS_5 = FuzzySet(function=Gaussian_MF(0.693124, 0.306512), term='cluster5')
MF_test = LinguisticVariable([FS_1, FS_2, FS_3, FS_4, FS_5], concept='test')
FS.add_linguistic_variable('test', MF_test)

FS_6 = FuzzySet(function=Gaussian_MF(0.291063, 0.286069), term='cluster1')
FS_7 = FuzzySet(function=Gaussian_MF(0.485543, 0.194097), term='cluster2')
FS_8 = FuzzySet(function=Gaussian_MF(0.757718, 0.233106), term='cluster3')
FS_9 = FuzzySet(function=Gaussian_MF(0.273670, 0.206791), term='cluster4')
FS_10 = FuzzySet(function=Gaussian_MF(0.678934, 0.260165), term='cluster5')
MF_symptoms = LinguisticVariable([FS_6, FS_7, FS_8, FS_9, FS_10], concept='symptoms')
FS.add_linguistic_variable('symptoms', MF_symptoms)

FS_11 = FuzzySet(function=Gaussian_MF(0.565012, 0.000236), term='cluster1')
FS_12 = FuzzySet(function=Gaussian_MF(0.104576, 0.055930), term='cluster2')
FS_13 = FuzzySet(function=Gaussian_MF(0.411053, 0.000280), term='cluster3')
FS_14 = FuzzySet(function=Gaussian_MF(-0.381682, 0.713394), term='cluster4')
FS_15 = FuzzySet(function=Gaussian_MF(1.565839, 0.774989), term='cluster5')
MF_action = LinguisticVariable([FS_11, FS_12, FS_13, FS_14, FS_15], concept='action')
FS.add_linguistic_variable('action', MF_action)


# end of automatically generated code #